winget install --id=Python.Python -e  ; 
winget install --id=Microsoft.VisualStudioCode -e  ; 
winget install --id=BraveSoftware.BraveBrowser -e  ; 
winget install --id=LibreOffice.LibreOffice -e  ; 
winget install --id=Spotify.Spotify -e  ; 
winget install --id=Discord.Discord -e  ; 
winget install --id=AntibodySoftware.WizTree -e  ; 
winget install --id=Valve.Steam -e ; 
winget install --id=Microsoft.WindowsTerminal -e  ; 
winget install --id=PuTTY.PuTTY -e 